services:
  db:
    image: postgres:15
    container_name: planmate-db
    restart: always
    environment:
      POSTGRES_DB: planmate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: planmate-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db-data: